export const GameState = {
    npcs:[],
    bullets:[],
    planets:[],
    player:null,
    camera:null,
    cameraRecoilOffset:null,
    gameOver:null,
    scene:null,
    sun:null,
    clock:null,
    zoom:{
        level:1,
        speed:0.1,
        min:0.5,
        max:3
    },
    fps:{
        sinceLast:0,
        frameCount:0,
        sinceLastLog:0
    },
    paused:false,
    npcUUID:0,
    planetUUID:0,
    timeDial:1,
    dialActive:false
}